---
project:
  application-name: '@pom.name@'
  version: '@project.version@'

spring:
  webflux:
    base-path: /nhn-adapter/api
    multipart:
      max-in-memory-size: 50MB
  http:
    codecs:
      max-in-memory-size: 50MB
  web:
    error:
      include-message: always

server:
  port: 8080

management:
  server:
    port: 8090
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,env,prometheus,health"
    enabled-by-default: true

digdir:
  audit:
    application-name: no.difi.meldingsutveksling.nhn-adapter:nhn-adapter-app
    application-environment: ${spring.application.environment}
    filters:
      admin-header: false
      bearer-token: true
      ip-address: true
    prometheus:
      counter: true

nhn:
  services:
    ar:
      username: ${NHN_SERVICES_USERNAME}
      password: ${NHN_SERVICES_PASSWORD}
    flr:
      username: ${NHN_SERVICES_USERNAME}
      password: ${NHN_SERVICES_PASSWORD}
    msh:
      source-system: "digidir"

oauth2:
  helse-id:
    client-id: ${NHN_CLIENT_ID}
    private-key: ${NHN_PRIVATE_KEY}

keystore:
  path: ${KEYSTORE_VALUE}
  alias: ${KEYSTORE_ALIAS}
  password: ${KEYSTORE_PASSWORD}
  type: ${KEYSTORE_TYPE:JKS}

logging:
  level:
    org.springframework.http.codec.json: INFO
    org.springframework.core.codec: INFO

temp:
  threshold: 10000000
  initial-buffer-size: 100000

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'optional:file:/etc/config/'

